src/Entity/PhraseAccueil.php
<?php

namespace App\Entity;

use App\Repository\PhraseAccueilRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PhraseAccueilRepository::class)]
class PhraseAccueil
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 500)]
    private $Content;

    #[ORM\Column(type: 'string', length: 255)]
    private $Auteur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
	<head>

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link rel="stylesheet" href="{{ asset('assets/css/Header.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/css/Footer.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/css/Fonts.css') }}">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"> {% block stylesheets %}{% endblock %}{% block GridCSS %}{% endblock %}{% block javascripts %}{% endblock %}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

	</head>

		<body
			id="Body">

			{# <div style="width:50%; background-color:red; opacity:30%; height: 100vh; position: fixed; top:0; left:0; z-index:999999999999999999">
					CHECKER
					</div> 
					<div style="width:100%; background-color:blue; opacity:30%; height: 50vh; position: fixed; bottom:0; left:0; z-index:999999999999999999">
					CHECKER
					</div> 
			
					<div style="width:2px; background-color:black; opacity:30%; height: 100vh; position: fixed; bottom:0; left:25%; z-index:999999999999999999">
					
					</div> 
			
					<div style="width:2px; background-color:black; opacity:30%; height: 100vh; position: fixed; bottom:0; left:50%; z-index:999999999999999999">
					
					</div> 
			
					<div style="width:2px; background-color:black; opacity:30%; height: 100vh; position: fixed; bottom:0; left:75%; z-index:999999999999999999">
					
					</div> 
			
					<div style="width:100%; background-color:black; opacity:30%; height: 2px; position: fixed; bottom:25vh; left:0%; z-index:999999999999999999">
					
					</div> 
			
					<div style="width:100%; background-color:black; opacity:30%; height: 2px; position: fixed; bottom:75vh; left:0%; z-index:999999999999999999">
					
					</div> 
			
					<div style="width:100%; background-color:black; opacity:30%; height: 2px; position: fixed; bottom:50vh; left:0%; z-index:999999999999999999">
					
					</div>  #}

			<div class="Wrapper" id="HeaderWrapper">
				<div class="FirstPart" id="firstpart">

					<button class="mobileMenuBtn" onclick="OpenMenu()">
						<img src="assets/img/Bars.svg" alt="" class="mobileMenuBars">
						</button>


					<div class="Title" id="Title">

				
					

						<a href="{{ path('app_accueil') }}">
							<img src="{{ asset('assets/img/EXCEPTIO.svg') }}" alt="" class="Header_ExceptioLogo">

						</a>

						<a href="{{ path('app_esperluette') }}">
							<img src="{{ asset('assets/img/Esperluette.svg') }}" alt="" class="HeaderEspeluette">
						</a>

				

					</div>


					<div class="Links" id="Menu">

						<a href="{{ path('app_realisation') }}">
							&nbsp;&nbsp;réalisations&nbsp;
						</a>

						<br class="HeaderBR">

						<a href="{{ path('app_studio') }}">
							&nbsp; studio&nbsp;
						</a>

						<br class="HeaderBR">

						<a href="{{ path('app_contact') }}">
							&nbsp; contact&nbsp;
						</a>

						<br class="HeaderBR">

					</div>


					<div class="SocialContainer" id="SocialMenu">

						<div class="Social">

							<a href="https://www.linkedin.com/company/exceptio-studio/">

								<img src="{{ asset('assets/img/Linkedin_Icon.png') }}" alt="linkedin" class="SocialIcon">

							</a>

							<a href="https://www.instagram.com/exceptio.studio/?hl=fr">

								<img src="{{ asset('assets/img/Instagram_Icon.png') }}" alt="instagram" class="SocialIcon">

							</a>

							<a href="https://www.facebook.com/exceptio.studio/">

								<img src="{{ asset('assets/img/Facebook_icon.png') }}" alt="facebook" class="SocialIcon">

							</a>


						</div>
					</div>

				

				</div>
				<div id="PhraseContainer" style="width: 100%; background-color:black;">
					<div
						class="Phrase " id="Phrase">
						{# {{Phrase.content}} <img src="assets/img/Esperluette.svg" alt="" class="phraseEsperluette"> {{Phrase.content}} & {{Phrase.content}} & {{Phrase.content}} #}

						<div class="phraseContent">
							{{Phrase.content}}
						</div>
						<img src="assets/img/Esperluette.svg" alt="" class="phraseEsperluette">
						<div class="phraseContent">
							{{Phrase.content}}
						</div>
						<img src="assets/img/Esperluette.svg" alt="" class="phraseEsperluette">
						<div class="phraseContent">
							{{Phrase.content}}
						</div>
						<img src="assets/img/Esperluette.svg" alt="" class="phraseEsperluette">
						<div class="phraseContent">
							{{Phrase.content}}
						</div>

					</div>

					<div class="Phrase " id="Auteur" style="display:none;">

						<div class="phraseContent">
							{{Phrase.auteur}}
						</div>

						<img src="assets/img/Esperluette.svg" alt="" class="phraseEsperluette">
						<div class="phraseContent">
							{{Phrase.auteur}}
						</div>
						<img src="assets/img/Esperluette.svg" alt="" class="phraseEsperluette">
						<div class="phraseContent">
							{{Phrase.auteur}}
						</div>
						<img src="assets/img/Esperluette.svg" alt="" class="phraseEsperluette">
						<div class="phraseContent">
							{{Phrase.auteur}}
						</div>

					</div>

				</div>

			</div>

			<div class="mobileMenu" id="mobileMenu">

				<a href="{{ path('app_realisation') }}">
					&nbsp;&nbsp;réalisations&nbsp;
				</a>

				<br >

				<a href="{{ path('app_studio') }}">
					&nbsp; studio&nbsp;
				</a>

				<br >

				<a href="{{ path('app_contact') }}">
					&nbsp; contact&nbsp;
				</a>
				
					<br >

				<button onclick="CloseMenu()">
					&nbsp;X&nbsp;
				</button>

			</div>


			{% block body %}{% endblock %}

			<div class="FooterContainer">


				<div class="SocialBar">

					<div class="Footer_Title">


						<a href="{{ path('app_accueil') }}">
							<img src="{{ asset('assets/img/EXCEPTIO_WHITE.svg') }}" alt="" class="Footer_ExceptioLogo">

						</a>

						<a href="{{ path('app_esperluette') }}">
							<img src="{{ asset('assets/img/Esperluette_white.svg') }}" alt="" class="Footer_Espeluette">
						</a>

					</div>

					<a href="https://www.linkedin.com/company/exceptio-studio/" target="blank">
						<img src="{{ asset('assets/img/Linkedin_Icon.png') }}" alt="" class="SocialIcon_Footer">
					</a>
					<a href="https://www.instagram.com/exceptio.studio/?hl=fr" target="blank">
						<img src="{{ asset('assets/img/Instagram_Icon.png') }}" alt="" class="SocialIcon_Footer">
					</a>
					<a href="https://www.facebook.com/exceptio.studio/" target="blank">
						<img src="{{ asset('assets/img/Facebook_icon.png') }}" alt="" class="SocialIcon_Footer">
					</a>

				</div>

			</div>
			<script src="{{ asset('assets/js/arrayImg.js') }}"></script>

			<script src="{{ asset('assets/js/Header.js') }}"></script>
			<script src="{{ asset('assets/js/MobileMenu.js') }}"></script>
		</body>
	</html>